// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/zero-one-cloud/notification/internal/biz"
	"github.com/zero-one-cloud/notification/internal/conf"
	"github.com/zero-one-cloud/notification/internal/data"
	"github.com/zero-one-cloud/notification/internal/server"
	"github.com/zero-one-cloud/notification/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(env *conf.Env, confServer *conf.Server, confData *conf.Data, bootstrap *conf.Bootstrap, logger log.Logger) (*kratos.App, func(), error) {
	db := data.NewMysqlCmd(bootstrap, logger)
	client := data.NewRedisCmd(confData, logger)
	dataData, cleanup, err := data.NewData(bootstrap, db, client, logger)
	if err != nil {
		return nil, nil, err
	}
	smsRepo := data.NewSmsRepo(dataData, logger)
	smsUseCase := biz.NewSmsUseCase(smsRepo, logger)
	emailRepo := data.NewEmailRepo(dataData, logger)
	emailUseCase := biz.NewEmailUseCase(emailRepo, logger)
	notificationService := service.NewNotificationService(smsUseCase, emailUseCase, logger)
	grpcServer := server.NewGRPCServer(confServer, notificationService, logger)
	httpServer := server.NewHTTPServer(confServer, notificationService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
